default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: minha_rotina_development
  port: 5433

test:
  <<: *default
  database: minha_rotina_test
  port: 5433

production:
  <<: *default
  database: minha_rotina_production
  username: minha_rotina
  password: <%= ENV['MINHA_ROTINA_DATABASE_PASSWORD'] %>